name: classic_snake
description: classic snake game

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0
#1.0.0+4
environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  toast:
  shared_preferences: ^2.3.2
  google_mobile_ads: ^4.0.0
  wakelock_plus: ^1.2.8
  firebase_core_web: ^2.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: true
  image_path: "icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Mail
      fonts:
        - asset: assets/fonts/Mali-Bold.ttf
        - asset: assets/fonts/Mali-BoldItalic.ttf
        - asset: assets/fonts/Mali-Italic.ttf
        - asset: assets/fonts/Mali-Medium.ttf
        - asset: assets/fonts/Mali-MediumItalic.ttf
        - asset: assets/fonts/Mali-Regular.ttf
          weight: 900